name             'chefs-gem'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures chefs-gem'
long_description 'Installs/Configures chefs-gem'
version          '0.1.0'
